# MCPify Configuration Sample
# This file demonstrates all available configuration options

server:
  # Transport method: "stdio" for standard input/output, "http" for HTTP server
  transport: "http"
  
  http:
    # Server host (use 127.0.0.1 for localhost, 0.0.0.0 for all interfaces)
    host: "127.0.0.1"
    
    # Server port
    port: 8080
    
    # Session timeout for HTTP transport
    session_timeout: "5m"
    
    # Maximum concurrent connections
    max_connections: 100
    
    # CORS configuration
    cors:
      enabled: true
      origins:
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
        - "https://your-frontend-domain.com"

# Logging configuration
logging:
  # Log level: "debug", "info", "warn", "error"
  level: "info"
  
  # Log format: "json" or "text"
  format: "json"
  
  # Log output: "stdout", "stderr", or file path
  output: "stdout"

# OpenAPI configuration
openapi:
  # Path to OpenAPI specification (local file or URL)
  spec_path: "https://petstore3.swagger.io/api/v3/openapi.json"
  
  # Base URL for API requests
  base_url: "https://petstore3.swagger.io/api/v3"
  
  # Request timeout
  timeout: "30s"
  
  # Maximum retry attempts for failed requests
  max_retries: 3
  
  # Prefix for generated tool names (optional, defaults to empty)
  # tool_prefix: "api_"
  
  # Authentication configuration
  auth:
    # Authentication type: "none", "bearer", "basic", "api_key"
    type: "bearer"
    
    # Bearer token (for type: "bearer")
    token: "your-bearer-token-here"
    
    # Basic authentication (for type: "basic")
    # username: "your-username"
    # password: "your-password"
    
    # API key authentication (for type: "api_key")
    # api_key: "your-api-key"
    # api_key_name: "X-API-Key"  # Header name or query parameter name
    # api_key_in: "header"       # "header" or "query"
    
    # Custom authentication headers
    headers:
      "X-Custom-Auth": "custom-value"
  
  # Custom headers for all requests
  headers:
    "User-Agent": "MCPify/1.0.0"
    "Accept": "application/json"
    "Content-Type": "application/json"
  
  # Path filtering - exclude these paths from tool generation
  exclude_paths:
    - "/health"
    - "/metrics"
    - "/docs"
    - "/swagger*"
    - "/openapi*"
  
  # Path filtering - only include these paths (if specified, only these will be included)
  # include_paths:
  #   - "/api/v1/*"
  #   - "/users/*"
  #   - "/posts/*"

# Security configuration
security:
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 100
  
  # Maximum request size
  request_size_limit: "1MB"
