# Example configuration demonstrating dynamic header forwarding
server:
  transport: "http"
  http:
    host: "localhost"
    port: 3000

openapi:
  spec_path: "https://api.example.com/openapi.json"
  base_url: "https://api.example.com"
  
  # Authentication configuration
  auth:
    type: "bearer"
    token: "your-static-token-here"
    
    # Dynamic auth headers using valueFrom
    headers:
      - header:
          name: "X-API-Key"
          valueFrom: "request.headers['x-mcpify-provider-data'].apikey"
      - header:
          name: "X-Client-ID"
          valueFrom: "request.headers['x-mcpify-provider-data'].client.id"
      - header:
          name: "X-Client-Secret"
          valueFrom: "request.headers['x-mcpify-provider-data'].client.secret"
  
  # General headers (static and dynamic)
  headers:
    - header:
        name: "User-Agent"
        value: "MCPify/1.0.0"
    - header:
        name: "Accept"
        value: "application/json"
    - header:
        name: "Authorization"
        valueFrom: "request.headers['authorization']"
    - header:
        name: "X-Forwarded-For"
        valueFrom: "request.headers['x-forwarded-for']"
    - header:
        name: "X-Request-ID"
        valueFrom: "request.headers['x-request-id']"
    - header:
        name: "X-Custom-Header"
        valueFrom: "request.headers['x-mcpify-provider-data'].custom.value"

  timeout: 30s
  max_retries: 3
  tool_prefix: "example"

# CORS configuration
cors:
  enabled: true
  origins:
    - "http://localhost:3000"
    - "https://your-frontend.com"

# Security configuration
security:
  rate_limiting:
    enabled: true
    requests_per_minute: 100
